name: RELEASE
on:
    push:
        branches:
            - main
env:
    NODE_VERSION: 18.15.0
    PNPM_VERSION: 7.27.1
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    create-pr-and-publish:
        name: Create PR and publish
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-environment
              with:
                  node-version: "${{ env.NODE_VERSION }}"
                  pnpm-version: "${{ env.PNPM_VERSION }}"
            - name: Create PR and publish
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  version: pnpm changeset version
                  commit: "ci(changeset): versioning packages"
                  title: "ci(changeset): versioning packages"
